name: Deploy Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Adjust to your Go version

      - name: Run go mod tidy
        run: |
          cd backend/backend
          go mod tidy

      - name: Restart myapp.service
        run: |
          sudo systemctl stop myapp.service
          sudo systemctl start myapp.service
